# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f0b79fc0feea2938c7f9ff2867735f966b81b784b26b36a0c7630ff3204a6104691617842fbbc3bb36e3335b144f28749024e2b1851bcae959c97941bedc437

test:
  secret_key_base: b87c0816d72b021f4b2843e07aad06b8abea65d917ee11ee94801a67e0cb7c0cbb590dfb831f083330b8bdc82c0277d484c503bd4342457c34a3d9f16540936b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
