module ApplicationHelper

  FACTS =
    ["Maine (Listeni/ˈmeɪn/; French: État du Maine) is a state in the New England region of the northeastern United States, bordered by the Atlantic Ocean to the east and south; New Hampshire to the west; and the Canadian provinces of Quebec to the northwest and New Brunswick to the northeast",
    "Maine is both the northernmost and easternmost portion of New England",
    "It is known for its scenery—its jagged, mostly rocky coastline, its low, rolling mountains, its heavily forested interior, and picturesque waterways—as well as for its seafood cuisine, especially lobster and clams",
    "Maine is the northernmost U.S state with an Atlantic coastline, but in spite of its maritime position it has a continental climate even in coastal cities such as its largest city Portland",
    "For thousands of years, indigenous peoples were the only inhabitants of the territory that is now Maine",
    "At the time of European encounter, several Algonquian-speaking peoples inhabited the area",
    "The first European settlement in Maine was by the French in 1604 on Saint Croix Island, by Pierre Dugua, Sieur de Mons",
    "The first English settlement in Maine, the short-lived Popham Colony, was established by the Plymouth Company in 1607",
    "A number of English settlements were established along the coast of Maine in the 1620s, although the rugged climate, deprivations, and conflict with the local peoples caused many to fail over the years",
    "As Maine entered the 18th century, only a half dozen European settlements had survived",
    "Patriot and Loyalist forces contended for Maine's territory during the American Revolution and the War of 1812",
    "Maine was part of the Commonwealth of Massachusetts until 1820 when it voted to secede from Massachusetts",
    "On March 15, 1820, it was admitted to the Union as the 23rd state under the Missouri Compromise",
    "Maine is the 39th most extensive and the 41st most populous of the 50 United States",
    "With respect to crime rates, Maine is also often considered the safest state in the U.S",
    "The Canadian province of Quebec is to the northwest",
    "Maine is both the northernmost state in New England and the largest, accounting for almost half the region's entire land area",
    "Maine is the only state to border only one other state (New Hampshire to the west)",
    "Maine is the easternmost state in the United States both in its extreme points and its geographic center",
    "The municipalities of Eastport and Lubec are, respectively, the easternmost city and town in the United States",
    "Estcourt Station is Maine's northernmost point, as well as the northernmost point in New England",
    "Maine's Moosehead Lake is the largest lake wholly in New England, as Lake Champlain is located between Vermont, New York and Quebec",
    "A number of other Maine lakes, such as South Twin Lake, are described by Thoreau in The Maine Woods (1864)",
    "Mount Katahdin is both the northern terminus of the Appalachian Trail, which extends southerly to Springer Mountain, Georgia, and the southern terminus of the new International Appalachian Trail which, when complete, will run to Belle Isle, Newfoundland and Labrador",
    "Maine has several unique geographical features",
    "Machias Seal Island and North Rock, off its easternmost point, are claimed by both the U.S and Canada and are within one of four areas between the two countries whose sovereignty is still in dispute, but it is the only one of the disputed areas containing land",
    "Also in this easternmost area in the Bay of Fundy is the Old Sow, the largest tidal whirlpool in the Western Hemisphere",
    "Maine is the least densely populated U.S. state east of the Mississippi River",
    "It is called the Pine Tree State; about 83% of its land is forested",
    "In the forested areas of the interior lie much uninhabited land, some of which does not have formal political organization into local units (a rarity in New England)",
    "The Northwest Aroostook, Maine unorganized territory in the northern part of the state, for example, has an area of 2,668 square miles (6,910 km2) and a population of 10, or one person for every 267 square miles (690 km2)",
    "Maine is in the temperate broadleaf and mixed forests biome",
    "The land near the southern and central Atlantic coast is covered by the mixed oaks of the Northeastern coastal forests",
    "The remainder of the state, including the North Woods, is covered by the New England-Acadian forests",
    "Maine has almost 230 miles (400 km) of coastline (and 3,500 miles (5,600 km) of tidal coastline)",
    "West Quoddy Head is the easternmost piece of land in the contiguous 48 United States",
    "Along the famous rock-bound coast of Maine are lighthouses, beaches, fishing villages, and thousands of offshore islands, including the Isles of Shoals, which straddle the New Hampshire border",
    "There are jagged rocks and cliffs and many bays and inlets",
    "Inland are lakes, rivers, forests, and mountains",
    "This visual contrast of forested slopes sweeping down to the sea has been summed up by American poet Edna St",
    "Vincent Millay of Rockland and Camden, Maine, in 'Renascence': The coast of Maine near Acadia National Park Boothbay Harbor 'All I could see from where I stood Was three long mountains and a wood; I turned and looked the other way, And saw three islands in a bay.' Geologists describe this type of landscape as a 'drowned coast', where a rising sea level has invaded former land features, creating bays out of valleys and islands out of mountain tops",
    "A rise in the elevation of the land due to the melting of heavy glacier ice caused a slight rebounding effect of underlying rock; this land rise, however, was not enough to eliminate all the effect of the rising sea level and its invasion of former land features",
    "Much of Maine's geomorphology was created by heavy glacial activity at the end of the last ice age",
    "Prominent glacial features include Somes Sound and Bubble Rock, both part of Acadia National Park on Mount Desert Island",
    "Carved by glaciers, Somes Sound is considered to be the only fjord on the eastern seaboard and reaches depths of 175 feet (50 m). The extreme depth and steep drop-off allow large ships to navigate almost the entire length of the sound. These features also have made it attractive for boat builders, such as the prestigious Hinckley Yachts",
    "Bubble Rock is what is known as a 'glacial erratic' and is a large boulder perched on the edge of Bubble Mountain in Acadia National Park",
    "By analyzing the type of granite, geologists were able to discover that glaciers carried Bubble Rock to its present location from the town of Lucerne, Maine — 30 miles (48 km) away",
    "The Iapetus Suture runs through the north and west of the state being underlain by the ancient Laurentian terrane and the south and east underlain by the Avalonian terrane",
    "Acadia National Park is the only national park in New England",
    "Areas under the protection and management of the National Park Service include: Acadia National Park near Bar Harbor Appalachian National Scenic Trail Maine Acadian Culture in St",
    "John Valley Roosevelt Campobello International Park near Lubec Saint Croix Island International Historic Site at Calais Autumn in Stratton Maine experiences a humid continental climate (Köppen climate classification Dfb), with warm (although generally not hot), humid summers",
    "Winters are cold and snowy throughout the state, and are especially severe in the northern parts of Maine",
    "Coastal areas are moderated somewhat by the Atlantic Ocean, resulting in milder winters and cooler summers in immediate coastal areas",
    "Daytime highs are generally in the 75–80 °F (24–27 °C) range throughout the state in July, with overnight lows in the high 50s °F (around 15 °C)",
    "January temperatures range from highs near 32 °F (0 °C) on the southern coast to overnight lows averaging below 0 °F (−18 °C) in the far north",
    "The state's record high temperature is 105 °F (41 °C), set in July 1911, at North Bridgton",
    "Precipitation in Maine is evenly distributed year-round, but with a slight summer maximum in northern/northwestern Maine and a slight late-fall or early-winter maximum along the coast due to 'nor'easters' or intense cold-season storms",
    "In coastal Maine, the late spring and summer months are usually driest – a rarity across the Eastern United States",
    "Maine has fewer days of thunderstorms than any other state east of the Rockies, with most of the state averaging less than 20 days of thunderstorms a year",
    "Tornadoes are rare in Maine, with the state averaging fewer than two per year, mostly occurring in the southern part of the state",
    "In January 2009, a new record low temperature for the state was set at Big Black River of −50 °F (−46 °C), tying the New England record",
    "Annual precipitation varies from 909 mm (35.8 in) in Presque Isle, to 1,441 mm (56.7 in) in Acadia National Park",
    "Misty Morning, Coast of Maine Arthur Parton (1842–1914)",
    "Between 1865 and 1870, Brooklyn Museum Main article: History of Maine Maine State House, designed by Charles Bulfinch, built 1829–1832 The original inhabitants of the territory that is now Maine were Algonquian-speaking Wabanaki peoples including the Abenaki, Passamaquoddy, Maliseet and Penobscot",
    "The first European settlement in what is now called Maine was in 1604 on Saint Croix Island, by Pierre Dugua, Sieur de Mons, including Samuel de Champlain, the noted explorer",
    "The French named the entire area Acadia, including the portion that later became the state of Maine",
    "The first English settlement in Maine was established by the Plymouth Company at Popham in 1607, the same year as the settlement at Jamestown, Virginia",
    "The Popham colonists returned to England after 14 months",
    "Two Jesuit missions were established by the French: one on Penobscot Bay in 1609, and the other on Mount Desert Island in 1613",
    "The same year, Castine was established by Claude de La Tour",
    "In 1625, Charles de Saint-Étienne de la Tour erected Fort Pentagouet to protect Castine",
    "The coastal areas of western Maine first became the Province of Maine in a 1622 land patent",
    "Eastern Maine north of the Kennebec River was more sparsely settled and was known in the 17th century as the Territory of Sagadahock. A second settlement was attempted at a place called York, in 1623 by English explorer and naval Captain Christopher Levett, granted 6,000 acres (24 km2) by King Charles I of England. That settlement also failed",
    "Central Maine was formerly inhabited by people of the Androscoggin tribe, also known as Arosaguntacook",
    "The Androscoggin were a tribe in the Abenaki nation. They were driven out of the area in 1690 during King William's War. They were relocated at St. Francis, Canada, which was destroyed by Rogers' Rangers in 1759, and is now Odanak",
    "The other Abenaki tribes suffered several severe defeats, particularly during Dummer's War, with the capture of Norridgewock in 1724 and the defeat of the Pequawket in 1725, which greatly reduced their numbers",
    "They finally withdrew to Canada, where they were settled at Bécancour and Sillery, and later at St. Francis, along with other refugee tribes from the south",
    "The province within its current boundaries became part of Massachusetts Bay Colony in 1652",
    "Maine was much fought over by the French, English and allied natives during the 17th and early 18th centuries, who conducted raids against each other, taking captives for ransom or, in some cases, adoption by Native American tribes",
    "For instance, in early 1692, the Abenaki raided York, killing about 100 of the English settlers and taking another estimated 80 villagers hostage",
    "The Abenaki took captives taken during raids of Massachusetts in Queen Anne's War of the early 1700s to Kahnewake, a Catholic Mohawk village near Montreal, where some were adopted and others ransomed",
    "After the British defeated the French in Acadia in the 1740s, the territory from the Penobscot River east fell under the nominal authority of the Province of Nova Scotia, and together with present-day New Brunswick formed the Nova Scotia county of Sunbury, with its court of general sessions at Campobello",
    "American and British forces contended for Maine's territory during the American Revolution and the War of 1812, and British forces occupied eastern Maine in both conflicts",
    "The treaty concluding revolution was ambiguous about Maine's boundary with British North America",
    "The territory of Maine was confirmed as part of Massachusetts when the United States was formed, although the final border with British territory was not established until the Webster-Ashburton Treaty of 1842",
    "Maine was physically separate from the rest of Massachusetts",
    "Long-standing disagreements over land speculation and settlements led to Maine residents and their allies in Massachusetts proper forcing an 1807 vote in the Massachusetts Assembly on permitting Maine to secede; the vote failed",
    "Secessionist sentiment in Maine was stoked during the War of 1812 when Massachusetts pro-British merchants opposed the war and refused to defend Maine from British invaders",
    "In 1819, Massachusetts agreed to permit secession if voters in Maine approved",
    "Due to these considerations and rapid population growth, in 1820 Maine voted to secede from Massachusetts",
    "The secession and formation of the state of Maine as the 23rd state occurred on March 15, 1820 as part of the Missouri Compromise, which geographically limited the spread of slavery and enabled the admission to statehood of Missouri the following year, keeping a balance between slave and free states",
    "Maine's original capital was Portland, Maine's largest city, until it was moved to Augusta in 1832 to make it more central within the state",
    "The principal office of the Maine Supreme Judicial Court remains in Portland",
    "The 20th Maine, under the command of Colonel Joshua Lawrence Chamberlain, defended Little Round Top at the Battle of Gettysburg",
    "Its soldiers prevented the Union Army from being flanked by the Confederate Army",
    "Four U.S. Navy ships have been named USS Maine in honor of the state",
    "There is no definitive explanation for the origin of the name 'Maine'",
    "The state legislature in 2001 adopted a resolution establishing Franco-American Day, which stated that the state was named after the former French province of Maine",
    "Other theories mention earlier places with similar names, or claim it is a nautical reference to the mainland",
    "The history of the name of Maine began with James Sullivan's 1795 'History of the District of Maine'",
    "He made the unsubstantiated allegation that the Province of Maine was a compliment to the queen of Charles I, Henrietta Maria, who once 'owned' the Province of Maine in France",
    "This was quoted by almost all Maine historians until the 1845 Agnes Strickland biography established that she had no connection to the Province of Maine in France",
    "King Charles I married Henrietta Maria in 1625, three years after the name Maine first appeared on the charter",
    "A new theory, set forth by Carol B Smith Fisher, is that The Province of MAINE was first chosen by Sir Ferdinando Gorges in 1622 to honor the village where his ancestral roots first took hold on English soil",
    "'MAINE' appears in the Domesday Book of 1086 in reference to the county of Dorset, that is today Broadmayne, just southeast of Dorchester",
    "The generally held view amongst British place name scholars is that Mayne in Dorset is Brythonic, corresponding to modern Welsh 'maen', plural 'main' or 'meini'",
    "Some early spellings are: MAINE 1086, MEINE 1200, MEINES 1204, MAYNE 1236",
    "Today the actual village is known as BROADMAYNE, which is primitive Welsh or Brythonic, 'main' meaning rock or stone, considered to be a reference to the many large sarsens still present around Little Mayne farm, half a mile northeast of Broadmayne village",
    "The first known record of the name appears in an August 10, 1622, land charter to Sir Ferdinando Gorges and Captain John Mason, English Royal Navy veterans, who were granted a large tract in present-day Maine that Mason and Gorges 'intend to name the Province of Maine'",
    "Mason had served in the Royal Navy in the Orkney Islands where the chief island is called Mainland, a more likely name derivation for these English sailors than the French province",
    "A year later, in 1623, the English naval captain Christopher Levett, exploring the New England coast, wrote: 'The first place I set my foote upon in New England was the Isle of Shoals, being Ilands [sic] in the sea, above two Leagues from the Mayne.' Initially, several coastal tracts along the coast of New England were referred to as Main or Maine (cf. the Spanish Main)",
    "A reconfirmed and enhanced April 3, 1639, charter from England's King Charles I gave Sir Ferdinando Gorges increased powers over his new province and stated that it 'shall forever hereafter, be called and named the PROVINCE OR COUNTIE OF MAINE, and not by any other name or names whatsoever...' Whatever the origin, the name was fixed in 1665 when the King's Commissioners ordered that the 'Province of Maine' be entered from then on in official records",
    "Maine is the only state whose name has exactly one syllable, and is the only state to border only one other",
    "The population density of the state is 41.3 people per square mile, making it the least densely populated state in New England, the American northeast, the eastern seaboard, of all of the states with an Atlantic coastline and of all of the states east of the Mississippi River",
    "The mean population center of Maine is located in Kennebec County, just east of Augusta",
    "The Greater Portland metropolitan area is the most densely populated with nearly 40% of Maine's population",
    "As explained in detail under 'Geography', there are large tracts of uninhabited land in some remote parts of the interior",
    "At the 2010 Census, 94.4% of the population was non-Hispanic White, 1.1% non-Hispanic Black or African American, 0.6% American Indian and Alaska Native, 1.0% Asian, 0.1% from some other race and 1.4% of two or more races",
    "1.3% of Maine's population was of Hispanic, Latino, or Spanish origin",
    "Maine has the highest percentage of French Americans among U.S states",
    "It also has the highest percentage of non-Hispanic whites of any state, at 94.4% of the total population, according to the 2010 Census",
    "In 2011, 89.0% of all births in the state were to two non-Hispanic white parents",
    "The state has the highest percentage of current French speakers of any state; most are descended from Quebecois immigrants who arrived between 1840 and 1930, and New Brunswick prior to 1842",
    "In northern Maine, (particularly Aroostook County), Acadians still speak French at home, since their relatives live in neighboring New Brunswick",
    "Census figures show that Maine has the highest percentage of people speaking French at home of any state: 5.28% of Maine households are French-speaking, compared with 4.68% in Louisiana",
    "French-speakers are the state's chief linguistic minority; the 2000 Census reported 92.25% of Maine residents aged five and older spoke only English at home",
    "Maine does not have an official language, but the most widely spoken language in the state is English",
    "The upper St",
    "John River valley area was once part of the so-called Republic of Madawaska, before the frontier was decided in the Webster-Ashburton Treaty of 1842",
    "Over one quarter of the population of Lewiston, Waterville, and Biddeford are Franco-American",
    "Most of the residents of the Mid Coast and Down East sections are chiefly of British heritage",
    "Smaller numbers of various other groups, including Irish, Italian and Polish, have settled throughout the state since the late 19th and early 20th century immigration waves.",
    "According to the Association of Religion Data Archives (ARDA), the religious affiliations of Maine in 2010 were: Catholic Church – 28% Protestant – 7% Evangelical Protestant - 4% The Catholic Church was the largest religious institution with 202,106 members",
    "The United Methodist Church had 28,329 members The United Church of Christ had 22,747 members Other religions – 1.7% Non-Christian religions include Hinduism, Islam, Buddhism and Bahá'í",
    "In 2010, a study named Maine as the least religious state in the United States",
    "The Bureau of Economic Analysis estimates that Maine's total gross state product for 2010 was $52 billion",
    "Its per capita personal income for 2007 was US$33,991, 34th in the nation",
    "As of August 2013, Maine're: Catholic Church – 28% Protestant – 7% Evangelical Protestant - 4% The Catholic Church was the largest religious institution with 202,106 members",
    "The United Methodist Church had 28,329 members The United Church of County is known for its potato crops",
    "Western Maine aquifers and springs are a major source of bottled water",
    "Maine is also the home of The Jackson Laboratory, the world's largest non-profit mammalian genetic research facility and the world's largest supplier of genetically purebred mice",
    "Maine has an income tax structure containing two brackets, 6.5% to 7.95% of personal income",
    "Prior to July 2013, Maine had four brackets: 2%, 4.5%, 7%, and 8.5%",
    "Maine's general sales tax rate is 5.5%, temporarily raised from 5% until June 30, 2015",
    "The state also levies charges of 7% on lodging and prepared food and 10% on short-term auto rentals",
    "Commercial sellers of blueberries, a Maine staple, must keep records of their transactions and pay the state 1.5 cents per pound ($1.50 per 100 pounds) of the fruit sold each season",
    "All real and tangible personal property located in the state of Maine is taxable unless specifically exempted by statute",
    "The administration of property taxes is handled by the local assessor in inco DeLorme, both located in Yarmouth",
    "Maine is esalso levies charges of 7% on lodging and prepared food and 10% on short-term auto rentals",
    "Commercial sellers of blueberries, a Maine staple, must keep records of their transactions and pay the state 1.5 cents per pound ($1.50 per 100 pounds) of the fruit sold each season",
    "All real and tangible personal property located in the state of Maine is taxable unless specifically exempted by statute",
    "The administration of property taxes is handled by the local assessor in inco DeLorme, both located in Yars on short-term auto rentals",
    "Commercial sellers of blueberries w the state 1.5 cents per pound ($1.50 per 100 pounds) of the fruit sold each season",
    "Both are served daily by many major airlines to destinationr transactions and pay the state 1.5 cents per pound ($1.50 pce 100 pounds) of the fruit sold each season",
    "All real and tangairoperty taxes is handled by the local assessor in inco DeLorme, both located in Yars on short-term auto rentals",
    "Commercial sellers of blueberries w the state 1.5 cents per pound ($1.50 pna both located in Yars on short-term auto rentals",
    "The executive branch is responsible for the execution of the laws created by the Legislature and is headed by the Governor of Maine (currently Paul LePage)",
    "The Governor is elected every four years; no individual may serve more than two consecutive terms in this office",
    "The current attorney general of Maine is Janet Mills",
    "As with other state legislatures, the Maine Legislature can by a two-thirds majority vote from both the House and Senate override a gubernatorial veto",
    "Maine is one of seven states that do not have a lieutenant governor",
    "The judicial branch is responsible for interpreting state laws",
    "The highest court of the state is the Maine Supreme Judicial Court",
    "The lower courts are the District Court, Superior Court and Probate Court",
    "All judges except for probate judges serve full-time, are nominated by the Governor and confirmed by the Legislature for terms of seven years",
    "Probate judges serve part-time and are elected by the voters of each county for four-year terms",
    "Maine is divided into political jurisdictions designated as counties",
    "In 1860 there were 16 counties in the state, ranging in size from 370 to 6,829 square miles (958 to 17,700 km2)",
    "Maine has had two independent governors recently (James B. Longley, 1975–1979 and Angus King, 1995–2003)",
    "Maine state politicians, Republicans and Democrats alike, are noted for having more moderate views than many in the national wings of their respective parties",
    "Maine is an alcoholic beverage control state",
    "On May 6, 2009, Maine became the fifth state to legalize same-sex marriage; however, the law was repealed by voters on November 3, 2009",
    "On November 6, 2012, Mairtarian Party of Maine In state general elections, Maine voters tend to accept independent and third-party candidates more frequently than most states",
    "In the 1936 presidential election, Franklin D. Roosevelt received the electoral votes of every state other than Maine and Vermont; these were the only two states in the nation that never voted for Roosevelt in any of his presidential campaigns, though Maine was closely fought in 1940 and 1944",
    "In the 1960s, Maine began to lean toward the Democrats, especially in presidential elections",
    "In 1968, Hubert Humphrey became just the second Democrat in half a century to carry Maine, perhaps because of the presence of his running mate, Maine Senator Edmund Muskie, although the state voted Republican in every presidential election in the 1970s and 1980s",
    "Since 1969, two of Maine's four electoral votes have been awarded based on the winner of the statewide election; the other two go to the highest vote-getter in each of the state's two congressional districts",
    "Every other state except Nebraska gives all its electoral votes to the candidate who wins the popular vote in the state at large, without regard to performance within districts",
    "Ross Perot achieved a great deal of success in Maine in the presidential elections of 1992 and 1996",
    "In 1992, as an independent candidate, Perot came in second to Democrat Bill Clinton, despite the longtime presence of the Bush family summer home in Kennebunkport",
    "In 1996, as the nominee of the Reform Party, Perot did better in Maine than in any other state",
    "Maine has voted for the Democratic candidate in six successive presidential elections, casting its votes for Bill Clinton twice, Al Gore in 2000, John Kerry in 2004, and Barack Obama in 2008 and 2012",
    "Although Democrats have carried the state in presidential elections in recent years, Republicans have largely maintained their control of the state's U.S. Senate seats, with Edmund Muskie, William Hathaway and George J. Mitchell being the only Maine Democrats serving in the U.S. Senate in the past fifty years",
    "In the 2010 midterm elections, Republicans made major gains in Maine. They captured the governor's office as well as majorities in both chambers of the state legislature for the first time since the early 1970s. However, in 2012 elections Democrats managed to recapture both houses of Maine Legislature",
    "Maine's U.S. senators are Republican Susan Collins and Independent Angus King",
    "The governor is Republican Paul LePage",
    "The state's two members of the United States House of Representatives are Democrat Chellie Pingree and Republican Bruce Poliquin",
    "An organized municipality has a form of elected local government which administers and provides local services, keeps records, collects licensing fees, and can pass locally binding ordinances, among other responsibilities of self-government",
    "The governmental format of most organized towns and plantations is the town meeting, while the format of most cities is the council-manager form",
    "As of 2013 the organized municipalities of Maine consist of 23 cities, 431 towns, and 34 plantations. Collectively these 488 organized municipalities cover less than half of the state's territory",
    "Maine also has 3 Reservations: Indian Island, Indian Township Reservation, and Pleasant Point Indian Reservation",
    "The largest municipality in Maine, by population, is the city of Portland (pop",
    "64,249)",
    "The smallest city by population is Eastport (pop 1,640)",
    "The largest town by population is Brunswick (pop 20,278)",
    "The smallest town by population is Frye Island, a resort town which reported zero year-round population in the 2000 Census; one plantation, Glenwood Plantation, Maine, also reported a permanent population of zero",
    "In the 2000 census, the smallest town aside from Frye Island was Centerville with a population of 26, but since that census, Centerville voted to disincorporate and therefore is no longer a town",
    "The next smallest town with a population listed in that census is Beddington (pop",
    "50 at the 2010 census)",
    "The largest municipality by land area is the town of Allagash, at 128 square miles (332 km2)",
    "The smallest municipality by land area is the plantation of Monhegan Island, at 0.86 square miles (2.2 km2)",
    "The smallest municipality by area that is not an island is Randolph, at 2.23 square miles (6 km2)",
    "Unorganized territory has no local government",
    "Administration, services, licensing, and ordinances are handled by the state government",
    "The unorganized territory of Maine consists of over 400 townships (towns are incorporated, townships are unincorporated), plus many coastal islands that do not lie within any municipal bounds",
    "The UT land area is slightly over one half the entire area of the State of Maine",
    "Year-round residents in the UT number approximately 9,000, about 1.3% of the state's total population, with many more people residing only seasonally within the UT",
    "Only four of Maine's sixteen counties (Androscoggin, Cumberland, Waldo and York) are entirely incorporated, although a few others are nearly so, and most of the unincorporated area is in the vast and sparsely populated Great North Woods of Maine. There are many such population clusters throughout Maine, but some examples from the municipalities appearing in the above listing are: Portland, South Portland, Cape Elizabeth, Westbrook, Scarborough, and Falmouth Lewiston and Auburn Bangor, Orono, Brewer, Old Town, and Hampden Biddeford, Saco and Old Orchard Beach Brunswick and Topsham Waterville, Winslow, Fairfield, and Oakland Presque Isle and Caribou",
    "Private schools are less common than public schools",
    "A large number of private elementary schools with under 20 students exist, but most private high schools in Maine can be described as 'semi-private.' This means that while it costs money to send children there, towns will make a contract with a school to take children from a town or School Administrative District at a slightly reduced rate",
    "Often this is done when it is deemed cheaper to subsidize private tuition than build a whole new school when a private one already exists",
    "The current state license plate design, introduced in 1999, depicts both the state bird and the state flower",
    "Lauren Oliver's book Delirium is set in Portland Charlotte Agell lives in Maine and has written several books set in Maine",
    "Gerald Warner Brace (1901–1978) lived in Deer Isle. All of his novels are set in New England, some in Maine",
    "Carolyn Chute (1947–) lives in Maine and set several novels in the fictional town of Egypt, Maine",
    "Terry Goodkind's The Law of Nines takes place in Maine",
    "John Irving wrote The Cider House Rules, a novel (and later a motion picture), set in several fictional Maine towns",
    "Sarah Orne Jewett (1849–1909) lived in South Berwick, Maine. Many of her novels and short stories were set in Maine",
    "John Cariani is an actor and playwright whose play 'Almost, Maine' is set in a fictional town in the state of Maine",
    "Dean Koontz wrote Night Chills, horror/suspense novel, which takes place in the fictional town of Black River, Maine",
    "H. P. Lovecraft, who set almost all of his stories in New England, occasionally mentions Maine",
    "Robert McCloskey (1914–2003 ) authored several beloved children's books including 'Make Way for Ducklings' and 'Blueberries for Sal.' Ruth Moore's novels were based almost entirely in Maine, although she rejected the label of 'regional writer.' Van Reid wrote The Moosepath League series of books, which are humorous adventures set in 19th-century Maine",
    "Harriet Beecher Stowe composed Uncle Tom's Cabin almost entirely in Brunswick, Maine",
    "Henry David Thoreau wrote The Maine Woods, which he visited during his stay at Walden Pond",
    "Lewis Robinson's novel Water Dogs and many of his short stories in Officer Friendly and Other Stories are set in Maine",
    "E. B. White lived in Brooklin, Maine and used Maine as the setting of Charlotte's Web. He also wrote many essays about his experiences in Maine including 'Once More to the Lake.' Kenneth Roberts (1885–1957) was a novelist of the Regionalist school, who wrote about Maine in works such as Arundel (novel)|Arundel, Northwest Passage (novel), Rabble in Arms and Boon Island (novel)",
    "Janet Chapman writes several series of paranormal romance and contemporary romance novels set in Maine",
    "John Connolly's Charlie Parker mystery series is based in and around Maine",
    "Richard Blanco, the poet who read at President Obama's second inauguration, lives in Bethel",
    "Carrie Jones set a series of best-selling books in Maine, the 'Need Pixies Series'",
    "Elisabeth Olgilvie born in MA but summered in Maine wrote High Tide at Noon and others about lobster families of Maine's Islands",
    "Belfast, Maine (1999) a documentary film on the quotidian life in Belfast, Maine by Frederick Wiseman",
    "The Beans of Egypt, Maine is a 1994 film directed by Jennifer Warren and is based on the 1985 novel by Carolyn Chute",
    "Carrie, based on the Stephen King novel, is set in Maine",
    "Casper, a 1995 children's film, is set in the town of Friendship, Maine",
    "The Cider House Rules, based on the John Irving novel, is set in several fictional Maine towns",
    "Dark Harbor, a 1998 mystery/suspense film is set on an island off the coast of Maine",
    "Darkness Falls, a 2003 horror film, is set in the fictional Maine town of Darkness Falls, but was filmed mostly in Australia",
    "Dreamcatcher, 2003 film adaptation of the Stephen King novel, is set in and around the fictional town of Derry, Maine",
    "Empire Falls, a motion picture based on Richard Russo's Pulitzer Prize-winning novel of the same name, was filmed almost entirely in Waterville and Skowhegan",
    "Graveyard Shift, a 1990 film adaptation of the Steven King novel, was filmed in Harmony, Maine but set in the fictional Gates Falls, Maine",
    "Todd Field's 2001 Academy Award–nominated film for Best Picture, In the Bedroom, is set in many towns throughout Maine including Rockland, Owls Head, Rockport, Camden, Thomaston, Trevette and Old Orchard Beach",
    "The Iron Giant, based on the novel The Iron Man by Ted Hughes, is an award-winning animated film that takes place in the fictional town of Rockwell, Maine, in the 1950s",
    "It Happened to Jane, a 1959 romantic comedy, is set in the fictional town of Cape Anne, Maine and prominently features the fictional Eastern & Portland Railroad, which was based loosely on the Boston & Maine Railroad and the New Haven Railroad",
    "Lake Placid, a 1999 comedy-horror film, is set by a fictional lake in Maine, starring Bridget Fonda and a large man-eating crocodile",
    "The Man Without a Face, a 1993 film starring Mel Gibson, was shot throughout Mid Coast Maine",
    "The Mist, a Stephen King novel, is set in Maine",
    "Pete's Dragon, a 1977 Walt Disney live-action/animated musical is set in Passamaquoddy, Maine Peyton Place, filmed in 1957, was set in New Hampshire but filmed in Camden region of Maine",
    "Red vs Blue, a comic science fiction video series, features a character named Maine",
    "The Shawshank Redemption, an award-winning 1994 movie, was set in Maine",
    "Storm of the Century, a miniseries based on the Stephen King novel, takes place in Maine, along with many other adaptations of his books",
    "Welcome to Mooseport was a 2004 movie set in the fictional city of Mooseport, Maine",
    "Wet Hot American Summer is set near Waterville, Maine",
    "'Home Alone 5' Takes place in Rockland, Maine",
    "Thinner, a novel by Stephen King, took place partly in Maine",
    "North Woods Law is a reality television series on the Animal Planet cable channel which follows Maine game wardens as they perform their duties; it premiered in March 2012",
    "'Augusta, Gone' (2001), a television drama about a teenager's descent into drug use, is set on Mount Desert Island, Maine",
    "Dark Shadows is set in the fictional coastal town of Collinsport, Maine",
    "Hawkeye Pierce, a central character of the television sitcom M*A*S*H, is a resident of the fictional town of Crabapple Cove, Maine. The role of Pierce was played by Alan Alda. The series was based upon the writings of Dr Richard Hornberger (writing as Richard Hooker), who following the war resided in Pittsfield",
    "Murder, She Wrote, a detective series starring Angela Lansbury, is set in the fictional Maine village of Cabot Cove, but filmed in Mendocino, California",
    "Murder in Small Town X was an unscripted drama series airing in 2001 with ten people competing to find a fictional killer in the town of Sunrise (Eastport, Maine) Kingdom Hospital, Stephen King's 2004 ABC mini-series, was set in Lewiston Haven, a science fiction series, is set in the fictional coastal town of Haven, Maine",
    "It is based on Stephen King's book 'The Colorado Kid.' Passions, a daytime soap opera is set in the fictional supernatural town of Harmony",
    "The first two months and opening credits were filmed in Camden and Belfast, Maine",
    "Once Upon a Time a series starring Lana Parrilla, Jennifer Morrison, Ginnifer Goodwin and Robert Carlyle is set in the fictional town of Storybrooke in Maine",
    "The Dead Zone, a science fiction series starring Anthony Michael Hall, is set in the fictional small town of Cleaves Mills",
    "Based on the novel by Stephen King",
    "Under the Dome, a science fiction series set in the fictional Maine town of Chester's Mill, based on the novel by Stephen King",
    "The titular town of the video game series Silent Hill (series) is located in Maine.[citation needed] Maine is featured in Bioshock: Infinite by Irrational Games",
    "The award-winning web series Ragged Isle tells the story of a small island lobstering community located twenty-one miles off the coast of Maine",
    "The island in the show is a fictionalized version of the real-life Maine island of Criehaven",
    "A citizen of Maine is known as a 'Mainer', though the term is often reserved for those whose roots in Maine go back at least three generations",
    "The term 'Downeaster' may be applied to residents of the northeast coast of the state",
    "The term 'Mainiac' is considered by some to be derogatory, but embraced with pride by others, and is used for a variety of organizations and for events such as the YMCA Mainiac Sprint Triathlon & Duathlon"]
end
